### ISSUE TITLE
generator-packing 生成工程 postcss 默认使用 .postcssrc.js 配置 stylelint 出现警告

### ISSUE THREAD

**Issue by yangfan86** [packingjs/packing#36]
default.less
```less
html,
body {
  width: 100%;
  height: 100%;
}

#root {
  display: flex;
  width: 100%;
  height: 100%;
  margin: 0 auto;
  overflow: auto;
  min-height: 100%;
  flex-direction: column;
}
```

.postcssrc.js
```javascript
module.exports = {
  parser: false,
  plugins: {
    stylelint: true
  }
};
```

webpack.serve.babel.js 未做修改。

执行命令
```
npm run stylelint
```
**执行通过，没有 lint 警告和错误**

执行命令
```
npm run start
```
**出现警告**

![cb02c92b74ab3141aca7425d3ac11d7f](https://user-images.githubusercontent.com/10629614/76753639-dfd45000-67bb-11ea-9060-9609dfb96df3.png)
